// 확장 전체(content script, popup, options)에서 공유하는 설정.
const NMA_DEFAULTS = {
  enabled: true,
  keywords: [
    // 단독 'suno'는 힌디어 '들어라'와 겹쳐 문맥이 있는 형태만 둔다.
    '#suno',
    'suno ai',
    'suno.ai',
    'made with suno',
    'generated by suno',
    'udio',
    '#udio',
    'riffusion',
    'mubert',
    'ai generated',
    'ai-generated',
    'generated by ai',
    'made with ai',
    'ai music',
    '#aimusic',
    'ai song',
    'ai cover',
    'ai 음악',
    'ai음악',
    'ai 생성',
    'ai 작곡',
    'ai로 만든',
  ],
  blockedChannels: [], // { id, name }
  allowedChannels: [], // { id, name }
  useSyntheticLabel: true,
  // 동영상 탭 첫 페이지(30개)만 세므로 대형 음악 채널(방송사·레이블)도 임계값을 넘는다. 기본은 끈다.
  useUploadRate: false,
  uploadRateThreshold: 14, // 최근 7일 업로드 수가 이 값 이상이면 AI 양산 채널로 판단
  lookahead: 5, // 플레이리스트에서 미리 검사할 다음 곡 수
};

const NMA_SETTING_KEYS = Object.keys(NMA_DEFAULTS);

async function nmaLoadSettings() {
  return chrome.storage.local.get(NMA_DEFAULTS);
}

async function nmaSaveSettings(patch) {
  await chrome.storage.local.set(patch);
}
